a = input('digite sth: ')
print('tipo do valor é : ', type(a))
print('é somente espaços',a.isspace())
print('é numero? ', a.isnumeric())
print('é alfabatico? ', a.isalpha())
print('é alfanumerico? ', a.isalnum())
print('é está maiuscula? ', a.isupper())
print('está em minuescula? ', a.islower())
print('está capitalizada? ' a.istitle())
